# Generated by Django 5.1.6 on 2026-03-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='report',
            field=models.JSONField(default=list),
        ),
    ]
