# Generated by Django 5.1.6 on 2026-03-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='heatmap_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
